Allow Arch package updates to complete
Previously, the following error was reported when running the
package manager update:

```
error: failed to commit transaction (conflicting files)
astyle: /usr/lib/libastyle.so.3 exists in filesystem
```

Passing --overwrite /usr/lib/libastyle.so.3 flag allows the previously
untracked file to be overwritten.

See: https://www.archlinux.org/news/astyle31-2-update-requires-manual-intervention/