Use http instead of https for Grammatech repos.
After upgrading the Gitlab runner on fife to 10.6, builds
began to fail with the following error:

Installing dist "elf".
> Error: No git references named 'HEAD'.
> While executing: (:INTERNAL QLOT.SOURCE.GIT::SHOW-REF QLOT.SOURCE.GIT::RETRIEVE-SOURCE-GIT-REF), in process listener(1).

See https://git.grammatech.com/synthesis/sel/-/jobs/136371 for an example.

Closer examination of the qlot source code yielded this snippet in
source/git.lisp:

```
(defun retrieve-source-git-ref (source)
  (check-type source source-git)
  (flet ((show-ref (pattern)
           (handler-case
               (let ((*standard-output* (make-broadcast-stream)))
                 (ppcre:scan-to-strings "^\\S+"
                                        (safety-shell-command "git"
                                                              (list "ls-remote"
                                                                    (source-git-remote-url source)
                                                                    pattern))))
             (shell-command-error ()
               (error "No git references named '~A'." pattern)))))
    (or (source-git-ref source)
        (show-ref (or (source-git-tag source)
                      (source-git-branch source)
                      "HEAD")))))
```

The call to `git ls-remote` was throwing an error, yielding the
"No git references named 'HEAD" message.  Using http removes
this error.  It appears certificate handling has changed during
the upgrade to gitlab-runner v10.6 - a suspicion that is confirmed
online.