Fixing build of Arch docker images
Currently, builds of synthesis Arch docker images are failing
due to the following error [1]:

```
error: failed to commit transaction (conflicting files)
nss: /usr/lib/p11-kit-trust.so exists in filesystem
```

The Arch documentation indicates that adding
`--overwrite /usr/lib/p11-kit-trust.so` to the pacman -Syu
invocation will resolve the issue [2].

[1] https://git.grammatech.com/synthesis/variegate/-/jobs/1364992
[2] https://www.archlinux.org/news/nss3511-1-and-lib32-nss3511-1-updates-require-manual-intervention/