Add tests illustrating problem with clang-projects
Currently in some cases clang-projects can not be copied because the
copy invokes `copy-files` which tries to recompile all of the files in
the project.  This recompilation fails because it takes
place *outside* of the project directory (specifically in a temporary
directory).

I think our current tests are papering over this bug by saving **full
paths** to relevant files in the compilation database, effectively
recompiling the original over and over instead of recompiling updated
copies in temporary directories.

See the following illustrative output given the new fixtures.

    SEL/TEST> (cl-user::untrace from-file)
    T
    SEL/TEST> (grep-bear-project)
    T
    SEL/TEST> (describe *project*)
    #<CLANG-PROJECT {100E886A83}>
      [standard-object]

    Slots with :INSTANCE allocation:
      FITNESS                        = NIL
      BUILD-COMMAND                  = "make"
      BUILD-TARGET                   = "grep"
      EVOLVE-FILES                   = (("grep.c" . #<CLANG {100E8FDC83}>))
      OTHER-FILES                    = NIL
      CURRENT-FILE-NAME              = NIL
      PROJECT-DIR                    = #P"/media/other/home/eschulte/lisp/local-projects/sel/test/etc/grep-pr..
      COMPILATION-DATABASE           = (((:ARGUMENTS "cc" "-c" "-o" "grep" "grep.c")..
      CLANG-CLASS                    = CLANG
    ; No value
    SEL/TEST> (compilation-database *project*)
    (((:ARGUMENTS "cc" "-c" "-o" "grep" "grep.c") (:DIRECTORY . "/tmp/file50cBPG")
      (:FILE . "grep.c")))
    SEL/TEST> (grep-project)
    T
    SEL/TEST> (describe *project*)
    #<CLANG-PROJECT {100E984B93}>
      [standard-object]

    Slots with :INSTANCE allocation:
      FITNESS                        = NIL
      BUILD-COMMAND                  = "make"
      BUILD-TARGET                   = "grep"
      EVOLVE-FILES                   = (("grep.c" . #<CLANG {100E992A63}>))
      OTHER-FILES                    = NIL
      CURRENT-FILE-NAME              = NIL
      PROJECT-DIR                    = #P"/media/other/home/eschulte/lisp/local-projects/sel/test/etc/grep-pr..
      COMPILATION-DATABASE           = (((:FILE..
      CLANG-CLASS                    = CLANG
    ; No value
    SEL/TEST> (compilation-database *project*)
    (((:FILE
       . "/media/other/home/eschulte/lisp/local-projects/sel/test/etc/grep-prj/grep.c")
      (:DIRECTORY
       . "/media/other/home/eschulte/lisp/local-projects/sel/test/etc/grep-prj/")
      (:COMMAND
       . "cc -c -o grep /media/other/home/eschulte/lisp/local-projects/sel/test/etc/grep-prj/grep.c")))
    SEL/TEST>

The effects of this difference are highlighted in the fact that it is
possible to copy *project* inside the grep-project fixture, but *not*
inside of the grep-bear-project fixture.  The following

    SEL/TEST> (copy *project*)
      0: (SOFTWARE-EVOLUTION-LIBRARY::COPY-FILES
          (("grep.c" . #<CLANG {100EBBDC83}>)))
    ; Evaluation aborted on #<SOFTWARE-EVOLUTION-LIBRARY:MUTATE {100EC688B3}>.
    SEL/TEST>

leads to this compilation error

    fatal error: 'getpagesize.h' file not found

because compilation does not take place inside of the test directory.